# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab43faa138c8dc99b340ae3cfb8202f51de67e886a8f3245a9375b36677c40b9cbf2d616de6f007d9fbbf42e18feb80a6bf4ad978ec525c16b4088296c19481f

test:
  secret_key_base: 32fa3e52c0195fe6706fd224132e658c9c51ad2acaa986de0a214e3b8e9a80c0d0a5d91822c3f674352238e8668caa6683f4755e9c61c5aa4e058aad9f417361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
